const ACTION_TYPE = {
  AUTHORIZE: `AUTHORIZE`,
  AUTHORIZATION_FAILED: `AUTHORIZATION_FAILED`,
  FETCH_OFFERS: `FETCH_OFFERS`,
  FETCH_REVIEWS: `FETCH_REVIEWS`,
  FETCH_FAVORITES: `FETCH_FAVORITES`,
  SET_CITY: `SET_CITY`,
  SWITCH_CITY: `SWITCH_CITY`,
  SET_SORTING_TYPE: `SET_SORTING_TYPE`,
  UPDATE_ACTIVE_CARD: `UPDATE_ACTIVE_CARD`,
  ADD_TO_FAVORITES: `ADD_TO_FAVORITES`,
  ADD_REVIEW: `ADD_REVIEW`
};

export default ACTION_TYPE;
