const ACTION_TYPE = {
  AUTHORIZE: `AUTHORIZE`,
  FETCH_OFFERS: `FETCH_OFFERS`,
  SET_CITY: `SET_CITY`,
  SET_SORTING_TYPE: `SET_SORTING_TYPE`,
  UPDATE_ACTIVE_CARD: `UPDATE_ACTIVE_CARD`
};

export default ACTION_TYPE;
